### ISSUE TITLE
Can we support `invoke local`

### ISSUE THREAD

**Issue by drusellers** [softprops/serverless-rust#20]
## 💡 Feature description

I'd love to be able to `serverless invoke local` to do some quick testing 

#### 💻 Basic example

My question is more if its even possible

**Comment by softprops** [comment]
Thanks for reaching out. This is currently blocked by this issue in serverless proper https://github.com/serverless/serverless/issues/5542#issuecomment-455839588

The good news is that since this is just a rust you can invoke the function by setting up a secondary bin and invoke it using cargo. I'll add create a reference example for that

**Comment by drusellers** [comment]
That would be great to have. Thank you.

**Comment by triptec** [comment]
Seems things are moving https://github.com/serverless/serverless/pull/5863

**Comment by softprops** [comment]
fantastic! I'll keep an eye on that

**Comment by ajmwagar** [comment]
serverless/serverless#5863 is now merged. Hopefully, we can add support for `invoke local --docker` soon.

**Comment by softprops** [comment]
I'll take a look this weekend

**Comment by softprops** [comment]
so I can get it ready by testing a local git source dependency on serverless but I'd want to hold off on publishing until the new invoke local support makes its way into a release, https://github.com/serverless/serverless/releases

**Comment by softprops** [comment]
@ajmwagar I've got a pull with a working example. I'll merge n ship when the next serverless framework release rolls around

**Comment by ajmwagar** [comment]
Great! I’m super excited to use this.

**Comment by softprops** [comment]
Me too. It was possible before with lambci but this makes things vastly more straight forward.

Great news. Serverless moves fast and just released a new version containing this feature. I'll update my test this weekend and publish a new version

**Comment by softprops** [comment]
https://github.com/softprops/serverless-rust/issues/30 looks like it may be a blocker. there appears to be an artifact packaging bug in serverless@1.39.0

**Comment by ajmwagar** [comment]
Dang. Hopefully it’ll get resolved soon.

Thanks for maintaining this awesome plugin!

**Comment by softprops** [comment]
a patch was released https://github.com/serverless/serverless/releases/tag/v1.39.1 Ill check again when I get home tonight and publish a release

**Comment by softprops** [comment]
published in serverless-rust@0.3.2

**Comment by Codii** [comment]
Hey, coming back on this after ages but is this still an issue ?
