### ISSUE TITLE
improve UX messaging when docker daemon is not accessible

### ISSUE THREAD

**Issue by softprops** [softprops/serverless-rust#32]
## 💡 Feature description

Currently if docker is not running ( perhaps or installed ) you get the following error

```
Serverless: Dockerized Rust build encountered an error: undefined 125.
```

It would be nicer to display a more useful message to help users find their way to success

#### 💻 Basic example

```
Serverless: Dockerized Rust build encountered an error: It looks like you don't have docker installed. {how to install...}
```

```
Serverless: Dockerized Rust build encountered an error: It looks like you don't have docker running. {how to start...}
```

**Comment by IslandUsurper** [comment]
Or at least say that it's required in the README.

**Comment by softprops** [comment]
added note in readme and better error messaging
