### ISSUE TITLE
Passing arbitrary `-e` to Docker run

### ISSUE THREAD

**Issue by maxcountryman** [softprops/serverless-rust#55]
Perhaps this is already possible and I'm missing it: I'm wondering if there's some way of passing through arbitrary `-e` flags to the Docker run command? In particular this would be nice now that softprops/lambda-rust#31 is merged in--even using a newer tag, there doesn't seem to be a way for library consumers to hook into e.g. a dev build.

**Comment by softprops** [comment]
there isn't a concrete interface to do that today but there is now experimental support for locally built lambdas which might solve this and other problems. 

https://github.com/softprops/serverless-rust#-experimental-local-builds

I plan on making this the default if things go well in the future but I don't have plans to remove docker support yet so I'll take this into consideration
