### ISSUE TITLE
Multiple handlers?

### ISSUE THREAD

**Issue by sporto** [softprops/serverless-rust#6]
Is it possible to have multiple handlers with one serverless.yml?
Like https://github.com/serverless/examples/tree/master/aws-golang-simple-http-endpoint
Seems I can only provide one. Thanks.

**Comment by softprops** [comment]
Hi @sporto this should be technically be possible but I don't have any examples to prove that. I'll see if I can do that this weekend

**Comment by softprops** [comment]
I crated a new example template with multiple http handlers here https://github.com/softprops/serverless-multi-lando

I'll also try to put together an example that mixes lando ( http focused ) with crowbar ( generic lambda event ) handlers soon
