### ISSUE TITLE
DEFAULT_DOCKER_TAG should be `:latest` by default?

### ISSUE THREAD

**Issue by brainstorm** [softprops/serverless-rust#63]
As you know I've modified [lambda-rust to play well with a bindgen crate](https://github.com/softprops/lambda-rust/pull/54) but when I try to deploy/invoke serverless-rust dev cycle, it'll keep pulling the old `0.2.6-rust-1.39.0`... I think it would make sense to leave it at `latest` and let users pass specific docker tags from previous versions if they need so?:

```diff
diff --git a/index.js b/index.js
index 1da00f7..66e1188 100644
--- a/index.js
+++ b/index.js
@@ -8,7 +8,7 @@ const { spawnSync } = require("child_process");
 const { homedir } = require("os");
 const path = require("path");

-const DEFAULT_DOCKER_TAG = "0.2.6-rust-1.39.0";
+const DEFAULT_DOCKER_TAG = "latest";
 const RUST_RUNTIME = "rust";
 const BASE_RUNTIME = "provided";
 const NO_OUTPUT_CAPTURE = { stdio: ["ignore", process.stdout, process.stderr] };
diff --git a/package.json b/package.json
index 66d3097..7cee6b7 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
   "name": "serverless-rust",
-  "version": "0.3.7",
+  "version": "0.3.8",
   "description": "Serverless framework plugin for Rustlang applications",
   "main": "index.js",
   "scripts": {
```

**Comment by softprops** [comment]
I'm rolling out experimental support for building locally in which might solve this issue and more. 

https://github.com/softprops/serverless-rust#-experimental-local-builds

I'm going to save this docker tag default for the next release
