### ISSUE TITLE
`sls deploy` fails due to build error (xml-rs)

### ISSUE THREAD

**Issue by kahlil29** [softprops/serverless-rust#72]
## 🐛 Bug description
Building an executable (first step of deploy or local invoke) fails due to build error (xml-rs)

#### 🤔 Expected Behavior
Should build executable successfully

#### 👟 Steps to reproduce
- Have `serverless` project with `serverless-rust` listed as a plugin in the `serverless.yml` file.
- Run `sls invoke local -f <myFunctionName>` OR `sls deploy` 

#### 🌍 Your environment
MacOS Catalina (Building for AWS Lambda)

serverless version: 1.71

rust-plugin version: 3.6 or 3.7 (latest released)

The issue is caused due to docker picking up an older version of the rust compiler (from what I understand) which causes the build failure of `xml-rs`. 
I think this could be fixed with the latest release (4.0) of this plugin. I just checked the CHANGELOG and found that there is a newer version of the docker image being pulled in, in that release.

**Comment by kahlil29** [comment]
Update: I ran `npm install https://github.com/softprops/serverless-rust` to get the latest version of the plugin and this seems to have pulled in the latest docker image with the newer version of the Rust compiler (that solves the `xml-rs` build error/issue). 
Leaving this here incase anyone else faces the same issue. 

P.S. `xml-rs` is a dependency of `rusoto-core` and some other `rusoto-x` crates so it seems very easy for someone to get his by this problem. 
I think this issue can be closed once version `4.0` of this plugin is released.

Also, thanks a lot to the authors/maintainers for the effort and really useful plugin! 😄

**Comment by softprops** [comment]
I'm going to close the issue since its been resolved but it will still be searchable if needed
