### ISSUE TITLE
Example with async handler?

### ISSUE THREAD

**Issue by amaurymartiny** [softprops/serverless-rust#73]
## 💡 Feature description

I would like to see examples using async handlers (is it supported already?). The echo, http and multi examples only show sync handlers.

#### 💻 Basic example

Does something like this already work?

```rust
fn main() {
    lambda!(handler)
}

async fn handler(
    event: Value,
    _: Context,
) -> Result<Value, HandlerError> {
    f().await?
}
```

**Comment by kahlil29** [comment]
Yes @amaurymartiny this works fine. 
It kind of has to work because a lot of AWS-related operations in `rusoto-*` are async functions. 
Did you try this out and it didn't work for you? What's the error?

**Comment by softprops** [comment]
@kahlil29 you'll likely want to check out the lasted rust runtime. It's not released yet but you can dependent on it as a git dependency. It's async by default

**Comment by softprops** [comment]
I'll be rolling out new examples soon

**Comment by softprops** [comment]
If it helps I posted a trivial example here https://github.com/softprops/dynomite/blob/master/dynomite/examples/lambda.rs

**Comment by kahlil29** [comment]
@amaurymartiny I hope this helps you. I think I was tagged by mistake 😅

**Comment by softprops** [comment]
@amaurymartiny all examples and templates have been updated to use the latest async version of the rust lambda runtime which is at this time an unreleased git dependency. When it's released I'll update to reflect the crates.io release
