### ISSUE TITLE
Support invoke/local

### ISSUE THREAD

**Issue by softprops** [softprops/serverless-rust#9]
add support for `serverless invoke local -f function-name`

**Comment by softprops** [comment]
while looking into this it seems very possible at the outset but now seems blocked by a conflict in what rust crowbar [expects in a provided context](https://github.com/ilianaw/rust-crowbar/blob/de24e28cc1c46e2b65ae8f3e8965be28b0b4f328/src/lib.rs#L177-L183) and what is provided by serverless' [fake invoker context](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/invokeLocal/invoke.py#L9-L38) namely to properties would need to be added to serverless's provided context `log_group_name` and `log_stream_name`. Aws' documentation for its python runtime does have a [complete list of attributes](https://docs.aws.amazon.com/lambda/latest/dg/python-context-object.html#python-context-object-props) but mentions `log_stream_name` may be None if the lambdas role doesn't have permission to write logs but is less clear about `log_group_name`. It should be relatively straightforward to add these to serverless's invoke harness.  so we may want to open an issue there and get feedback on what a patch may look like. 

In addition serverless's invoke conext returns an [memory_limit_in_mb  as an in  ](https://github.com/serverless/serverless/blob/9f1c3341cbe6da88810d792f2048556713b3fd4d/lib/plugins/aws/invokeLocal/invoke.py#L34) where crowbar [assumes a str](https://github.com/ilianaw/rust-crowbar/blob/de24e28cc1c46e2b65ae8f3e8965be28b0b4f328/src/lib.rs#L180). Since crowbar works  in production aws its likely its represented as a string and should be with serverless invoke context for consistency.

It's also work taking note that [crowbar has its own fake invoke context for testing](https://github.com/ilianaw/rust-crowbar/blob/de24e28cc1c46e2b65ae8f3e8965be28b0b4f328/test/test_liblambda.py#L70-L80) that we may want to reference for comparison

**Comment by softprops** [comment]
1.33 of severless framework was just released which should now make invoke local possible

**Comment by softprops** [comment]
closing to reopen for the new serverless runtime

**Comment by ajmwagar** [comment]
Doesn't work for me on Serverless 1.38.0.

Using your serverless-aws-rust template.
 
```
serverless invoke local -f hello -d '{"foo":"bar"}'
 ```

```
Serverless Error ---------------------------------------
 
  You can only invoke Node.js, Python, Java & Ruby functions locally.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           10.15.3
     Serverless Version:     1.38.0

```

Maybe reopen?

**Comment by ajmwagar** [comment]
Oops. I didn't see #20.

Thanks, Google. :/

Please disregard.
