### ISSUE TITLE
lambda-rust docker image based of al2 whereas the plugin BASE_RUNTIME is al

### ISSUE THREAD

**Issue by nicolas-pathlit** [softprops/serverless-rust#99]
Why wouldn't the plugin allow the use of the `provided.al2` runtime for consistency sake? I mean the plugin when performing a docker built compiles on an image that is based on **al2/glibc** (lambci/lambda:build-provided.al2), but then when packaging and deploying a lambda with serverless, it  targets a `al1` based runtime which requires **al1/musl** creating errors at the lambda execution like ***GLIBC_2.18 not found***

Any reason I am missing to not set the `const BASE_RUNTIME` to `const BASE_RUNTIME = "provided.al2";` in the `index.js` source and align these?

**Comment by jaronsummers** [comment]
It actually is set to provided.al2 in index.js already, this plugin is just never released anymore.

**Comment by nicolas-pathlit** [comment]
Very good point, thank you for sharing this.
